#!/bin/bash

# short: Run this WebHare

set -eo pipefail

exit_syntax()
{
  echo "Syntax: runkit @server run-webhare [--detach] [--rescue]"
  exit 1
}

DETACH=""
STARTUPOPT=""
DOCKEROPTS=()
ASSERVICE=""
REQUIREUNITS=""

while true; do
  if [ "$1" == "--detach" ]; then
    DETACH="1"
    shift
  elif [ "$1" == "--rescue" ]; then
    STARTUPOPT="/bin/bash"
    DOCKEROPTS+=(-ti)
    shift
  elif [ "$1" == "--dockeropt" ]; then
    shift
    DOCKEROPTS+=("$1")
    shift
  elif [ "$1" == "--privileged" ]; then
    DOCKEROPTS+=(--privileged)
    shift
  elif [ "$1" == "--requireunit" ]; then
    shift
    REQUIREUNITS="$REQUIREUNITS $1"
    shift
  elif [ "$1" == "--publishrescueport" ]; then
    shift
    DOCKEROPTS+=(--publish "$1:13679/tcp")
    DOCKEROPTS+=(--env WEBHARE_RESCUEPORT_BINDIP=0.0.0.0)
    shift
  elif [ "$1" == "--as-service" ]; then
    ASSERVICE="1"
    shift
  elif [ "$1" == "--help" ]; then
    exit_syntax
  elif [[ "$1" =~ ^-.* ]]; then
    echo "Invalid switch '$1'"
    exit 1
  else
    break
  fi
done

[ -n "$1" ] && exit_syntax

CMDLINE=()

if [ -n "$WHRUNKIT_CONTAINERNAME" ]; then
  configure_runkit_podman
  killcontainer "$WHRUNKIT_CONTAINERNAME"

  USEIMAGE="$(cat "$WHRUNKIT_TARGETDIR"/container.image)"
  # Looks like we have to launch this WebHare using podman

  if [ "$DETACH" == "1" ]; then
    DOCKEROPTS+=(--detach)
  else
    DOCKEROPTS+=(--rm)
  fi

  USEIP="$(cat "$WHRUNKIT_TARGETDIR"/container.ipv4 2>/dev/null || true)"
  if [ -z "$USEIP" ]; then
    # Find a free IP address
    for LASTOCTET in $(seq 2 253) ; do
      ISINUSE=0
      USEIP="${WHRUNKIT_NETWORKPREFIX}.${LASTOCTET}"
      for IP in $(cat $WHRUNKIT_DATADIR/*/container.ipv4 2>/dev/null || true); do
        if [ "$IP" == "$USEIP" ]; then
          ISINUSE=1
          break;
        fi
      done
      if [ "$ISINUSE" == "0" ]; then
        break;
      fi
    done
    [ "$ISINUSE" == "0" ] || die "Unable to find a free IP address"
    echo $USEIP > "$WHRUNKIT_TARGETDIR"/container.ipv4
  fi

 # if [ -z "$WHRUNKIT_TARGETDIR"/container.ipv4 ]; then
#    # Allocate a free IP address under

  if [ "$WHRUNKIT_CONTAINERENGINE" == "docker" ]; then
    CMDLINE+=(docker run -v "$WEBHARE_DATAROOT:/opt/whdata")
  else
    MOUNTFLAGS=""
    if [[ "$OSTYPE" != "darwin"* ]]; then
      MOUNTFLAGS=":Z" #on darwin this triggers lsetxattr error, see https://github.com/containers/podman-compose/issues/509#issuecomment-1162988103
    else
      DOCKEROPTS+=(--user="$(id -u):$(id -g)" --userns=keep-id)
    fi

    CMDLINE+=(podman run -v "$WEBHARE_DATAROOT:/opt/whdata"$MOUNTFLAGS)
  fi

  # Added --no-hosts - this easily breaks connectivity to the proxy server if it's aliased to ::1
  CMDLINE+=(-h "$WHRUNKIT_TARGETSERVER".docker
               --network "$WHRUNKIT_NETWORKNAME"
               --ip "$USEIP"
               -e TZ=Europe/Amsterdam
               --label runkittype=webhare
               --log-opt max-size=50m
               --log-opt max-file=5
               --no-hosts
               --name "$WHRUNKIT_CONTAINERNAME"
               "${DOCKEROPTS[@]}"
               "$USEIMAGE"
               $STARTUPOPT)

else
  CMDLINE=("$WHRUNKIT_WHCOMMAND" console)
fi

if [ -n "$ASSERVICE" ]; then

  configure_runkit_podman

  if ! hash systemctl 2>/dev/null ; then
    echo "No systemctl - cannot install systemd unit"
    exit 1
  fi

# In the interest of server stability, we will not put any runkit code on the webhare-startup path
# TODO using a temp file is nicer
cat > "/etc/systemd/system/$WHRUNKIT_CONTAINERNAME.service" << HERE
# This unitfile was generated by webhare-runkit's run-webhare.sh
[Unit]
Description=WebHare ${WHRUNKIT_TARGETSERVER}
After=${WHRUNKIT_CONTAINERENGINE}.service ${REQUIREUNITS}
Requires=${WHRUNKIT_CONTAINERENGINE}.service ${REQUIREUNITS}

[Service]
TimeoutStartSec=0
Restart=always

# Ensure any existing container gets out of the way
ExecStartPre=-"$WHRUNKIT_CONTAINERENGINE" stop $WHRUNKIT_CONTAINERNAME
ExecStartPre=-"$WHRUNKIT_CONTAINERENGINE" rm -f -v $WHRUNKIT_CONTAINERNAME
ExecStart=${CMDLINE[@]}
ExecStartPost=-"$WHRUNKIT_ROOT/bin/runkit" __oncontainerchange started "$WHRUNKIT_CONTAINERNAME"
ExecStopPost=-"$WHRUNKIT_ROOT/bin/runkit" __oncontainerchange started "$WHRUNKIT_CONTAINERNAME"

[Install]
WantedBy=multi-user.target
HERE

  systemctl daemon-reload
  systemctl enable "$WHRUNKIT_CONTAINERNAME" #ensure autostart
  systemctl start "$WHRUNKIT_CONTAINERNAME"
  exit 0
fi

exec "${CMDLINE[@]}"
